spring.application.name=CourseFlow
server.port=${SERVER_PORT:8080}
spring.profiles.default=standalone

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URL:https://caring-pangolin-516.clerk.accounts.dev/.well-known/jwks.json}
